"""Where the public projection bundle and study manifests live (ADR-0034 S1, S2).

Mirrors :mod:`dashboard_app.content.paths`: this is repository content, not
user data. The projection bundle is generated by
:mod:`scripts.dashboard.generate_btc_signal_quality_projection` (run at
build time, never inside a Streamlit render) and committed here; a study
manifest is small, curatorial metadata and is hand-authored directly as a
JSON file, not generated.
"""

from __future__ import annotations

from pathlib import Path

#: apps/dashboard/publication_data/ -- a sibling of src/, pages/, content/
#: and tests/.
PUBLICATION_DATA_ROOT = Path(__file__).resolve().parents[3] / "publication_data"

STUDY_MANIFESTS_ROOT = PUBLICATION_DATA_ROOT / "manifests"


def projection_bundle_path() -> Path:
    """Return the expected path of the committed public projection bundle.

    Does not check the file exists --
    :func:`dashboard_app.publication.validation.load_projection_bundle_from_path`
    is the fail-closed entry point for that.
    """
    return PUBLICATION_DATA_ROOT / "projection.json"


def study_manifest_path(slug: str) -> Path:
    """Return the expected file path for a study manifest's ``slug``.

    Does not check the file exists --
    :func:`dashboard_app.publication.validation.load_study_manifest_from_path`
    is the fail-closed entry point for that.
    """
    return STUDY_MANIFESTS_ROOT / f"{slug}.json"
