"""Predictive Research specification contracts, labelled matrix, and fold planner."""

from trading_framework.research.predictive.errors import (
    PredictiveExtraError,
    PredictiveMatrixError,
    PredictiveSpecError,
)
from trading_framework.research.predictive.estimators import (
    EstimatorDescription,
    EstimatorSpec,
    FittedPredictiveEstimator,
    NativeFeatureImportance,
    PredictiveEstimator,
    TaskType,
)
from trading_framework.research.predictive.exclusions import MatrixExclusionCounts
from trading_framework.research.predictive.features import (
    FeatureMatrixSpec,
    FeatureSpec,
    FeatureTransform,
)
from trading_framework.research.predictive.importance import (
    DEFAULT_PERMUTATION_REPEATS,
    FoldPrimaryGap,
    ImportanceTrace,
    PermutationImportance,
    permutation_feature_importance,
    primary_gap,
)
from trading_framework.research.predictive.labels import LabelKind, LabelSpec
from trading_framework.research.predictive.leaderboard import (
    LeaderboardRow,
    LeaderboardRowKind,
    LeaderboardRunSnapshot,
    PredictiveLeaderboard,
    build_predictive_leaderboard,
    primary_metric_for_task,
)
from trading_framework.research.predictive.matrix import (
    LabelledFeatureMatrix,
    build_labelled_feature_matrix,
)
from trading_framework.research.predictive.metrics import (
    CLASSIFICATION_DECISION_THRESHOLD,
    PREDICTIVE_METRICS_SCHEMA_VERSION,
    REGRESSION_DECISION_THRESHOLD,
    FinanceMetrics,
    MetricSource,
    PredictiveMetricsReport,
    SourceMetrics,
    StatisticalMetrics,
    build_predictive_metrics_report,
    default_decision_threshold,
    fold_train_targets,
)
from trading_framework.research.predictive.preprocessing import (
    PreprocessingSpec,
    PreprocessingStep,
    canonicalize_preprocessing_json,
    default_preprocessing_spec,
    require_train_only_fit_roles,
)
from trading_framework.research.predictive.selection import (
    DEFAULT_INNER_VALIDATION_FRACTION,
    DEFAULT_MAX_CANDIDATES,
    MAX_CANDIDATES_CAP,
    MIN_INNER_SPLIT_ROWS,
    CandidateFoldScore,
    CandidateSetSpec,
    FoldSelectionTrace,
    SelectionMetric,
    SelectionTrace,
    candidate_identity_hash,
    require_early_stopping_eval_roles,
    select_winning_index,
    split_inner_train_validation,
)
from trading_framework.research.predictive.spec import (
    PredictiveStudySpec,
    compute_definition_hash,
    load_predictive_study_spec,
    load_predictive_study_spec_from_dict,
)
from trading_framework.research.predictive.splitting import (
    FoldRole,
    PurgedWalkForwardSplitMode,
    PurgedWalkForwardSplitSpec,
    assign_purged_walk_forward_folds,
)
from trading_framework.research.predictive.windows import (
    MAX_LOOKBACK_BARS,
    MIN_EFFECTIVE_SAMPLE,
    MIN_LOOKBACK_BARS,
    WINDOW_ACCOUNTING_FILENAME,
    PaddingPolicy,
    RoleWindowAccounting,
    SequenceWindows,
    SequenceWindowSpec,
    WindowAccounting,
    build_sequence_windows,
    read_window_accounting,
    require_min_effective_sample,
    write_window_accounting,
)

__all__ = [
    "CLASSIFICATION_DECISION_THRESHOLD",
    "DEFAULT_INNER_VALIDATION_FRACTION",
    "DEFAULT_MAX_CANDIDATES",
    "DEFAULT_PERMUTATION_REPEATS",
    "MAX_CANDIDATES_CAP",
    "MAX_LOOKBACK_BARS",
    "MIN_EFFECTIVE_SAMPLE",
    "MIN_INNER_SPLIT_ROWS",
    "MIN_LOOKBACK_BARS",
    "PREDICTIVE_METRICS_SCHEMA_VERSION",
    "REGRESSION_DECISION_THRESHOLD",
    "WINDOW_ACCOUNTING_FILENAME",
    "CandidateFoldScore",
    "CandidateSetSpec",
    "EstimatorDescription",
    "EstimatorSpec",
    "FeatureMatrixSpec",
    "FeatureSpec",
    "FeatureTransform",
    "FinanceMetrics",
    "FittedPredictiveEstimator",
    "FoldPrimaryGap",
    "FoldRole",
    "FoldSelectionTrace",
    "ImportanceTrace",
    "LabelKind",
    "LabelSpec",
    "LabelledFeatureMatrix",
    "LeaderboardRow",
    "LeaderboardRowKind",
    "LeaderboardRunSnapshot",
    "MatrixExclusionCounts",
    "MetricSource",
    "NativeFeatureImportance",
    "PaddingPolicy",
    "PermutationImportance",
    "PredictiveEstimator",
    "PredictiveExtraError",
    "PredictiveLeaderboard",
    "PredictiveMatrixError",
    "PredictiveMetricsReport",
    "PredictiveSpecError",
    "PredictiveStudySpec",
    "PreprocessingSpec",
    "PreprocessingStep",
    "PurgedWalkForwardSplitMode",
    "PurgedWalkForwardSplitSpec",
    "RoleWindowAccounting",
    "SelectionMetric",
    "SelectionTrace",
    "SequenceWindowSpec",
    "SequenceWindows",
    "SourceMetrics",
    "StatisticalMetrics",
    "TaskType",
    "WindowAccounting",
    "assign_purged_walk_forward_folds",
    "build_labelled_feature_matrix",
    "build_predictive_leaderboard",
    "build_predictive_metrics_report",
    "build_sequence_windows",
    "candidate_identity_hash",
    "canonicalize_preprocessing_json",
    "compute_definition_hash",
    "default_decision_threshold",
    "default_preprocessing_spec",
    "fold_train_targets",
    "load_predictive_study_spec",
    "load_predictive_study_spec_from_dict",
    "permutation_feature_importance",
    "primary_gap",
    "primary_metric_for_task",
    "read_window_accounting",
    "require_early_stopping_eval_roles",
    "require_min_effective_sample",
    "require_train_only_fit_roles",
    "select_winning_index",
    "split_inner_train_validation",
    "write_window_accounting",
]
