"""Execution domain package."""

from trading_framework.execution.broker_sim import PaperBroker, PaperBrokerResult, PaperBrokerState
from trading_framework.execution.models import (
    BestBidAskSnapshot,
    ExecutionEvent,
    ExecutionEventType,
    Heartbeat,
    MarketFeedConnectionState,
    MarketFeedStatusSnapshot,
    OrderIntent,
    OrderSide,
    OrderStatus,
    OrderType,
    PaperAccountSnapshot,
    PaperPosition,
    PositionSide,
    RuntimeHealth,
    RuntimeStatusSnapshot,
    SimulatedFill,
    SimulatedOrder,
)
from trading_framework.execution.modes import ExecutionMode
from trading_framework.execution.repositories import (
    DEFAULT_RECENT_BAR_LIMIT,
    DEFAULT_RECENT_EVENT_LIMIT,
    DEFAULT_RECENT_FILL_LIMIT,
    DEFAULT_RECENT_ORDER_LIMIT,
    ExecutionReadModelQuery,
    ExecutionStateReader,
    ExecutionStateRepository,
    ExecutionStateWriter,
    RecentBarView,
    RecentExecutionEventView,
    RecentFillView,
    RecentOrderView,
    RuntimeStatusView,
)
from trading_framework.execution.runtime import (
    EmaMomentumLiveSignalEvaluator,
    LiveSignalEvaluation,
    LocalExecutionRuntimeSession,
    RuntimeDecisionStep,
    RuntimeDecisionStepResult,
    StrategyModelLiveSignalEvaluator,
    StrategyModelOrderAdapter,
    StrategyOrderDecision,
    StrategyOrderDecisionType,
    closed_bar_close_reference_quote,
    required_closed_bars_for_strategy,
    resolve_live_closed_bar_window,
)
from trading_framework.execution.safety import DRY_RUN_SAFETY_POLICY, ExecutionSafetyPolicy

__all__ = [
    "DEFAULT_RECENT_BAR_LIMIT",
    "DEFAULT_RECENT_EVENT_LIMIT",
    "DEFAULT_RECENT_FILL_LIMIT",
    "DEFAULT_RECENT_ORDER_LIMIT",
    "DRY_RUN_SAFETY_POLICY",
    "BestBidAskSnapshot",
    "EmaMomentumLiveSignalEvaluator",
    "ExecutionEvent",
    "ExecutionEventType",
    "ExecutionMode",
    "ExecutionReadModelQuery",
    "ExecutionSafetyPolicy",
    "ExecutionStateReader",
    "ExecutionStateRepository",
    "ExecutionStateWriter",
    "Heartbeat",
    "LiveSignalEvaluation",
    "LocalExecutionRuntimeSession",
    "MarketFeedConnectionState",
    "MarketFeedStatusSnapshot",
    "OrderIntent",
    "OrderSide",
    "OrderStatus",
    "OrderType",
    "PaperAccountSnapshot",
    "PaperBroker",
    "PaperBrokerResult",
    "PaperBrokerState",
    "PaperPosition",
    "PositionSide",
    "RecentBarView",
    "RecentExecutionEventView",
    "RecentFillView",
    "RecentOrderView",
    "RuntimeDecisionStep",
    "RuntimeDecisionStepResult",
    "RuntimeHealth",
    "RuntimeStatusSnapshot",
    "RuntimeStatusView",
    "SimulatedFill",
    "SimulatedOrder",
    "StrategyModelLiveSignalEvaluator",
    "StrategyModelOrderAdapter",
    "StrategyOrderDecision",
    "StrategyOrderDecisionType",
    "closed_bar_close_reference_quote",
    "required_closed_bars_for_strategy",
    "resolve_live_closed_bar_window",
]
